### ISSUE TITLE
64 weight file formatting

### ISSUE THREAD

**Issue by emilymak** [ElArkk/jax-unirep#105]
I'm looking to evotune the 64 node neural network. Is the correct formatting of the 64 weight file accessible in this code or how could I format the original weight files to be compatible with jax? Thanks!

**Comment by ElArkk** [comment]
Hi @emilymak 

At the moment, `jax-unirep` gets shipped with only the 1900 weights. Since the 256 and 64 models are stacked mLSTMs, I just realised that loading the original weights for them is a bit of a pain. I created a small PR to add those weights in.

Once merged you could then load them using `load_params`, either directly or after downloading them from the GitHub repo, depending on if we include them in the PyPi package by default.

**Comment by aaroncsolomon** [comment]
Hi @ElArkk - did you end up doing this? Or are the weights available for download and manual loading? Thanks!
