### ISSUE TITLE
Question about weights and using different architectures

### ISSUE THREAD

**Issue by pkinn** [ElArkk/jax-unirep#109]
Thanks for taking the time to make this, it's been incredibly helpful. I have a question about how the weights are accessed by unirep-jax as currently implemented, which relates to moving to the 64 node version of unirep. This is in part related to pull request #106. Also, I would be happy to try to implement this myself - I saw in the contribution guidelines you folks don't have a ton of spare time, but I definitely would need some guidance. 

The get_reps() function in featurize.py has the following code to get the weights:

    if params is None:
        params = load_params()[1]
    # Check that params have correct keys and shapes
    validate_mLSTM_params(params, n_outputs=mlstm_size)

`load_params` will by default use a couple of other functions to get the 1900 weights file which is packaged with jax-unirep. This file is a tuple of length 5, with the 0th entry being the embedding layer, the 1st entry being a weights dict corresponding to all the weights for unirep-1900. The 2nd and 4th entries in the tuple are empty, and the 3rd entry appears to be the layer that converts the LSTMs to amino acid predictions. 

I'm confused about one thing moving to the 64 or 256 versions of unirep which are deeper.

When I look at the 64-weights you have, the tuple that is loaded has length 11, with 3 extra dictionaries, presumably corresponding to the weights in the different layers of the unirep-64 implementation. However, in that case, I'd clearly need to load all of the params (i.e. entries 1,3,5, and 7). Am I correct in thinking that the `load_params()[1]` would need to be changed for deeper networks in order to get all of the param dicts?

Secondly, how could I actually go about applying the params to a deep neural network? Would I need to somehow copy the code from `evotuning_models.py` where it says, for instance:
```
 model_layers = (
        AAEmbedding(10),
        mLSTM(64),
        mLSTMHiddenStates(),
        mLSTM(64),
        mLSTMHiddenStates(),
        mLSTM(64),
        mLSTMHiddenStates(),
        mLSTM(64),
        mLSTMHiddenStates(),
        Dense(25),
        Softmax,
    )
    init_fun, apply_fun = serial(*model_layers)
```
And then somehow use the `apply_fun` similarly to how it's already used in `get_reps` when you say: 

```
h_final, c_final, h = vmap(partial(apply_fun, params))(embedded_seqs)
```

One thing (among many) I'm not sure about is how to get the `params` argument to be a list of separate dicts instead of individual dicts. I have never used Jax before or done much machine learning, so most of these are just based on inference from pre-existing code. 

Thanks again!

**Comment by ericmjl** [comment]
Hi @pkinn! My many apologies here. @ElArkk was finishing up his MSc thesis; he just finished last week! Meanwhile, I was busy trying to rear a child on paternity leave.

> This file is a tuple of length 5, with the 0th entry being the embedding layer, the 1st entry being a weights dict corresponding to all the weights for unirep-1900. The 2nd and 4th entries in the tuple are empty, and the 3rd entry appears to be the layer that converts the LSTMs to amino acid predictions.

Firstly, you're correct w.r.t. how the weights are structured! 

I had to re-read your question a few times to grok where I think the core issue is. So let me attempt an answer, and you can let me know if I've totally butchered it. 

We wrote the model layers following JAX's `stax`-style implementations. Though it helps to know how `stax` works, the tl;dr on how the weights are returned is this: The weights are returned in whatever way the `init_fun` implements it, and are then nested as deeply as the `init_fun`s are nested.

I think your goal is to use the mlstm256 and mlstm64 models with a top model. Is that correct? (This is the core assumption I'm making in the rest of my answer; if I've got it wrong, let me know what's the ultimate thing you're trying to accomplish so we can work backwards.) If so, you would want to extend the model code with more `stax` layers:

```python
from jax.experimental import stax

model_layers = (
    AAEmbedding(10),
    mLSTM(64),
    mLSTMHiddenStates(),
    mLSTM(64),
    mLSTMHiddenStates(),
    mLSTM(64),
    mLSTMHiddenStates(),
    mLSTM(64),

    # Top models start with mLSTMAvgHidden (by convention)
    mLSTMAvgHidden(),
    # Add two layers, one dense layer that results in 512-dim activations
    Dense(512), Relu(),
    # And then a linear layer to produce a 1-dim activation
    Dense(1)
)
init_fun, apply_fun = serial(*model_layers)
```

(FYI, I glanced [at the docs](https://elarkk.github.io/jax-unirep/advanced/#end-to-end-differentiable-models) to figure that one out -- even we have trouble remembering everything!)

Now, your `apply_fun` will be the thing you can `vmap`.

I don't think we have the pre-trained weights for the mLSTM64 and mLSTM256 models yet. But, at the same time, we haven't really had the need/opportunity to think about how to easily enable pre-trained weights to be drop-in replaced since the biggest use case of jax-unirep that we've had is as a protein descriptor generator from mLSTM1900. 

The thinking here is that the universe of models that jax-unirep users might want to write is large and varied. As a result, programmatically identifying which weights should be replaced in arbitrary model structures is difficult.
