### ISSUE TITLE
Evotuning with stop codons

### ISSUE THREAD

**Issue by kbyang** [ElArkk/jax-unirep#55]
Hello, I'm wondering if there is any consensus on whether or not we should include stop codons at the end of sequences used for evotuning. In the original repository's tutorial, there is a line that states: "Notice that by default format_seq does not include the stop symbol (25) at the end of the sequence. This is the correct behavior if you are trying to train a top model, but not if you are training UniRep representations." So this makes me assume that stop codons should not be included when creating representations for training a top model, but they should be included when evotuning. Is this correct?

**Comment by ElArkk** [comment]
Hi @kbyang !

In our reimplementation, we have adhered to the principles you have described. 

Internally, whenever we transform a protein sequence to its integer representation,  a start (24) and stop (25) symbol are appended to the beginning and end of the integer sequence respectively (see the function `aa_seq_to_int` in `utils.py`). 

However, if the `aa_seq_to_int` function is called in the context of the `get_reps` function, the stop symbol gets sliced off before calculating the representation (see `get_embedding` in `utils.py`). When performing evotuning, this does not happen (see `evotuning_pairs` in `evotuning.py`).

I think this to be the 'right' way of doing things at least when creating UniReps since the representations for the same protein sequence match up almost perfectly between the original UniRep `get_rep` function and our `get_reps`.

But I realise now that this behaviour is not obvious when looking at our codebase, and that it could be re-written in a cleaner way in the future (PR's always welcome! 😄 ).

**Comment by kbyang** [comment]
Thank you for the quick reply and all of your hard work re-implementing the model! That makes a lot of sense, I should have looked more closely.  

I'm curious if you have gotten evotuning to work in your hands. I am getting stochastic results testing with a small number of epochs (<100) on a few thousand training sequences. I've collected jackhmmer sequences, removed duplicates, and filtered them by levenshtein distance such that they have a similar length to the input sequence. So far only yielding small improvements in top model performance. Any general tips and advice?

**Comment by ericmjl** [comment]
@kbyang: @ElArkk can respond more clearly than I would, but it's generally been the same story with us. UniRep has been better at producing fixed-length descriptors for our proteins, and less so at evotuning. That said, I'm personally of the opinion that the evotuning protocol has a lot of levers (number of sequences, diversity of input sequences, etc.) that can all affect the performance of the top model in perhaps quite complex ways, so I think it's worth further systematic digging.

**Comment by kbyang** [comment]
@ericmjl I see, I'll try some different things and report back. Maybe over time we can accumulate some empirical guidelines for achieving better evotuning performance.

**Comment by ericmjl** [comment]
Wonderful, @kbyang. Definitely keep us posted.

Meanwhile, we'd love to encourage community contributions to the project, and if you're up for submitting a very small pull request that adds what @ElArkk posted to the README (even if verbatim!), we'd love to have your contribution on board.

**Comment by kbyang** [comment]
@ericmjl I'm currently a graduate student at NYU. I would love to help out, I will get to submitting a PR soon.
