### ISSUE TITLE
Parameters not properly being passed into get_reps functions?

### ISSUE THREAD

**Issue by hhefzi** [ElArkk/jax-unirep#59]
First off, thanks for the straight forward reimplementation of this, been very useful.

I've done some light evotuning and obtained weights, however when I pass the parameters to the get_rep function, it seems to default to the UniRep weights every other function call.

```python
from jax_unirep.utils import load_params
from jax_unirep import get_reps
import matplotlib.pyplot as plt

params = load_params(folderpath="20200707/iter_1/")[0]
mut_seq = 'PROTEIN'

mut_rep = get_reps(mut_seq)[0]
mut_rep2 = get_reps(mut_seq,params=params)[0]
mut_rep3 = get_reps(mut_seq,params=params)[0]
mut_rep4 = get_reps(mut_seq,params=params)[0]

fig,ax = plt.subplots()
ax.plot(range(0,1900),mut_rep[0]-mut_rep2[0]+.5) #shifted to visualize
ax.plot(range(0,1900),mut_rep[0]-mut_rep3[0])
ax.plot(range(0,1900),mut_rep[0]-mut_rep4[0]+.3) #shifted to visualize
ax.legend(['rep2','rep3','rep4'])
plt.show()
```

![index](https://user-images.githubusercontent.com/14252001/87864743-0dbfd180-c921-11ea-8c87-1fccf2bd8130.png)

Any idea what's going on?

**Comment by ericmjl** [comment]
@hhefzi thanks for pinging in.

@ElArkk was looking at it this morning in Basel. I'll be taking a look at the bug this afternoon in Cambridge (MA). (I have meetings all morning -_-".)

The starter code you provided is really helpful. (I took the liberty of formatting it nicely.) Thanks for that. We'll loop back with what we uncover.

**Comment by ericmjl** [comment]
@hhefzi, please check google/jax#3814 - I've tried some work to debug, but I'm running out of ideas too. [This gist](https://gist.github.com/ericmjl/fd9ccd067244bab514dafc4d6eb56cee#file-issue-59-debugging-ipynb) should give you a flavour for what I've tried. 

Just wondering too, have you dug into the source code to see what might be causing the oscillatory behaviour?

Until the oscillatory behaviour is cleared, I think the best way to guarantee idempotency is not within a single Python session, but across Python sessions. That means clearing kernel state/memory by restarting a Jupyter kernel or something like that before re-running.

**Comment by tanggis** [comment]
I ran into the same issue of oscillating behavior of `get_reps()`, only when `params` is passed in. I also confirmed that calling `get_reps()` on a batch of sequences work as expected, i.e. no oscillation among the sequences passed in the same call. Unfortunately, I have to call `get_reps()` multiple times because I can't rep all my sequences in a single call due to memory limit.

While getting to a workaround for myself, I noticed it seems to be the weights in the `params` variable that's changing after each `get_reps()` call. Sorry I haven't gotten a chance to look into the source for the cause, but I hope this gives you some clue to debug. MWE pasted below. 

```python
import numpy as np
from jax_unirep import load_params, get_reps

sequence = 'AAAA'

params = load_params(folderpath="test/iter_1")
for i in range(5):
    h_i0 = get_reps(sequence)[0][0],
    h_i = get_reps(sequence, params=params[0])[0][0]
    print(i, 
          np.sum(h_i0), 
          np.sum(h_i), 
          np.sum(params[0]['wh']), 
          np.sum(params[0]['wmh']), 
          np.sum(params[0]['wmx']), 
          np.sum(params[0]['wx']))
```
outputs: oscillating reps and weights.
```
0 346.76392 3.2205524 0.5631604 -0.36207837 0.13095234 117.01743
1 346.76392 2.1747289 -0.63283193 -0.0630296 0.34982795 15.586513
2 346.76392 3.2205524 0.56316 -0.3620776 0.13095237 117.017456
3 346.76392 2.1747289 -0.63283134 -0.06302984 0.34982803 15.5865135
4 346.76392 3.220552 0.5631602 -0.3620774 0.13095243 117.017456
```

Workaround
```python
import numpy as np
from jax_unirep import load_params, get_reps

sequence = 'AAAA'

#params = load_params(folderpath="test/iter_1")
for i in range(5):
    params = load_params(folderpath="test/iter_1")  # reloading params each time resets it
    h_i0 = get_reps(sequence)[0][0],
    h_i = get_reps(sequence, params=params[0])[0][0]
    print(i, 
          np.sum(h_i0), 
          np.sum(h_i), 
          np.sum(params[0]['wh']), 
          np.sum(params[0]['wmh']), 
          np.sum(params[0]['wmx']), 
          np.sum(params[0]['wx']))
```
No oscillation now!
```
0 346.76392 3.2205524 0.5631604 -0.36207837 0.13095234 117.01743
1 346.76392 3.2205524 0.5631604 -0.36207837 0.13095234 117.01743
2 346.76392 3.2205524 0.5631604 -0.36207837 0.13095234 117.01743
3 346.76392 3.2205524 0.5631604 -0.36207837 0.13095234 117.01743
4 346.76392 3.2205524 0.5631604 -0.36207837 0.13095234 117.01743
```

Unrelated to this but practically, I need to add the `reset_device_memory()` piece in the for loop, as suggested in #44, otherwise I'd run out of memory after a few iterations. Please let me know if you have figured out a better fix for that too.

Thank you so much for sharing this repo to the public!!

**Comment by hypostulate** [comment]
`params` is being mutated in `layers.mLSTM1900_batch.mLSTM1900_step`.

I think this change should solve it 
```
        wx = l2_normalize(params["wx"], axis=0) * params["gx"]
        wh = l2_normalize(params["wh"], axis=0) * params["gh"]
        wmx = l2_normalize(params["wmx"], axis=0) * params["gmx"]
        wmh = l2_normalize(params["wmh"], axis=0) * params["gmh"]

        # Shape annotation
        # (:, 10) @ (10, 1900) * (:, 1900) @ (1900, 1900) => (:, 1900)
        m = np.matmul(x_t, wmx) * np.matmul(h_t, wmh)

        # (:, 10) @ (10, 7600) * (:, 1900) @ (1900, 7600) + (7600, ) => (:, 7600)
        z = (
            np.matmul(x_t, wx)
            + np.matmul(m, wh)
            + params["b"]
        )
```

**Comment by ericmjl** [comment]
Yes, the change is being made in a branch! Thanks guys, this was
something we should have caught at the beginning and not let through.
The branch in question will also allow for flexible numbers of hidden
representation sizes, apart from the standard 1900, 256 and 64. 

On October 22, 2020, GitHub <notifications@github.com> wrote:
> params is being mutated in layers.mLSTM1900_batch.mLSTM1900_step.
>
> I think this change should solve it
>
> wx = l2_normalize(params["wx"], axis=0) * params["gx"] wh =
> l2_normalize(params["wh"], axis=0) * params["gh"] wmx =
> l2_normalize(params["wmx"], axis=0) * params["gmx"] wmh =
> l2_normalize(params["wmh"], axis=0) * params["gmh"] # Shape annotation
> # (:, 10) @ (10, 1900) * (:, 1900) @ (1900, 1900) => (:, 1900) m =

> np.matmul(x_t, wmx) * np.matmul(h_t, wmh) # (:, 10) @ (10, 7600) * (:,

> 1900) @ (1900, 7600) + (7600, ) => (:, 7600) z = ( np.matmul(x_t, wx)
> + np.matmul(m, wh) + params["b"] )

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ElArkk/jax-unirep/issues/59#issuecomment-714552503>,

or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAUCPDUNZPJJETAV3PYNX5DSMBB3LANCNFSM4PATSGEQ>.

**Comment by tanggis** [comment]
Thanks, @hypostulate ! `l2_normalize` does appear to oscillate `params`. So your fix should work! See below.

```python
for i in range(5):
    params['wx'] = l2_normalize(params["wx"], axis=0) * params["gx"]
    print(i, np.sum(params['wx']))
```
...output
```
0 117.01734
1 15.586511
2 117.01734
3 15.586513
4 117.01734
```

**Comment by hypostulate** [comment]
#84

**Comment by ericmjl** [comment]
Thanks both of you, I’m going to record this as an intellectual contribution in the docs. I myself couldn’t narrow down the cause of the oscillatory behavior. Props to y’all!
