### ISSUE TITLE
Why is the embedding sequence one longer than the protein sequence?

### ISSUE THREAD

**Issue by konstin** [ElArkk/jax-unirep#85]
I'm trying to use the per-residue embeddings of unirep and have obeserved that the hidden state sequence is one longer than the number of amino acids in the sequence. Judging from the `test_mLSTM1900` test, this is intended. Could you tell me why there is one extra hidden state?

For reference, this is the minimized code I'm using ([full source](https://github.com/sacdallago/bio_embeddings/blob/7b63361bd813f0a3cf354157cd01299b56d24fd9/bio_embeddings/embed/unirep_embedder.py#L35-L45)):

```python
from jax import vmap, partial
from jax_unirep.featurize import apply_fun
from jax_unirep.utils import get_embeddings, load_params_1900
embedded_seqs = get_embeddings([sequence])
h_final, c_final, h = vmap(partial(apply_fun, load_params_1900()))(embedded_seqs)
return h[0] # len(h[0]) == len(sequence) + 1
```

**Comment by ElArkk** [comment]
Hi @konstin ,

I'd say it's because we add a "start" amino-acid (aa) when integer-encoding the protein sequence before repping (actually, true to the original implementation, a "start" and a "stop" aa get added to either end of the sequence, but when using `get_reps` the "stop" aa gets removed again). 

The exact function in `jax-unirep` where this happens is `get_embedding` in `utils.py`. 
In the original implementation it's in `get_rep` in `unirep.py`.

I had another look at the tutorial in the original repo:

> Notice that by default format_seq does not include the stop symbol (25) at the end of the sequence. This is the correct behavior if you are trying to train a top model, but not if you are training UniRep representations.

So I guess we should actually not be excluding the "stop" symbol when evotuning, like we do now (see `evotuning_pairs` in `utils.py`). I never tested though how much this matters in reality.

**Comment by ElArkk** [comment]
See also https://github.com/ElArkk/jax-unirep/issues/55

**Comment by konstin** [comment]
Thanks!
